/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as KeysRouteImport } from './routes/keys'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as IntegrationsIdRouteImport } from './routes/integrations_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysRoute = KeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsIdRoute = IntegrationsIdRouteImport.update({
  id: '/integrations_/$id',
  path: '/integrations/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/integrations': typeof IntegrationsRoute
  '/keys': typeof KeysRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/integrations/$id': typeof IntegrationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/integrations': typeof IntegrationsRoute
  '/keys': typeof KeysRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/integrations/$id': typeof IntegrationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/integrations': typeof IntegrationsRoute
  '/keys': typeof KeysRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/integrations_/$id': typeof IntegrationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/integrations'
    | '/keys'
    | '/login'
    | '/setup'
    | '/integrations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/integrations'
    | '/keys'
    | '/login'
    | '/setup'
    | '/integrations/$id'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/integrations'
    | '/keys'
    | '/login'
    | '/setup'
    | '/integrations_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  IntegrationsRoute: typeof IntegrationsRoute
  KeysRoute: typeof KeysRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  IntegrationsIdRoute: typeof IntegrationsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys': {
      id: '/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof KeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations_/$id': {
      id: '/integrations_/$id'
      path: '/integrations/$id'
      fullPath: '/integrations/$id'
      preLoaderRoute: typeof IntegrationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  IntegrationsRoute: IntegrationsRoute,
  KeysRoute: KeysRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  IntegrationsIdRoute: IntegrationsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
